<?php
$students = [
    [
        "firstName" => "James",
        "lastName" => "Fields",
        "grades" => [12, 11, 15],
        "average" => -1
    ],
    [
        "firstName" => "Richard",
        "lastName" => "Stein",
        "grades" => [18, 12, 13],
        "average" => -1
    ],
    [
        "firstName" => "Mark",
        "lastName" => "Hartoff",
        "grades" => [9, 11, 10],
        "average" => -1
    ],
    [
        "firstName" => "Thomas",
        "lastName" => "Nestle",
        "grades" => [9, 8, 5],
        "average" => -1
    ],
    [
        "firstName" => "Jeremy",
        "lastName" => "Brent",
        "grades" => [18, 15, 16],
        "average" => -1
    ]
];
?>
<!DOCTYPE html>
<html lang="fr-FR">
<head>
  <meta charset="UTF-8">
  <title>JS1.1 – Variables</title>
</head>
<body>
    <?php
    foreach($students as $student)
    { ?>
<article class="">
    <header>
        <h1>Nom et prénom de l'étudiant</h1>
    </header>
    <section>
        <h2>Notes : </h2>
        <ul>
            <li>Note 1</li>
            <li>Note 2</li>
            <li>Note 3</li>
        </ul>
    </section>
    <footer>
        <h3>Moyenne des notes de l'étudiant </h3>
    </footer>
</article>
<?php } ?>
</body>
</html>

